NOT_STARTED = 0
ONGOING = 1
COMPLETED = 2
VALID_STATUSES = {NOT_STARTED, ONGOING, COMPLETED}

DEFAULT_PRIORITY = 0
MAX_PRIORITY = 999
DEFAULT_ONGOING_COMPLETION = 50.0

OPTIONAL_TASK = -1
UNSORTED = -1
NO_MILESTONE = 0

ENABLE_TUI_ORDER_BREADCRUMBS = True
ENABLE_TUI_UNICODE_PROGRESS = True
ENABLE_TUI_ROMAN_MILESTONES = True
TUI_PROGRESS_BAR_WIDTH = 10
TUI_TABLE_ROW_HEIGHT = 2
TUI_NOTIFICATION_MAX_VISIBLE = 3
TUI_NOTIFICATION_INFO_TIMEOUT_SECONDS = 2.0
TUI_NOTIFICATION_SUCCESS_TIMEOUT_SECONDS = 2.0
TUI_NOTIFICATION_WARNING_TIMEOUT_SECONDS = 4.0
TUI_NOTIFICATION_ERROR_TIMEOUT_SECONDS = 6.0

DEFAULT_TASK_GROUP_DESCRIPTION = "Task group"
DEFAULT_TASK_DESCRIPTION = "Task"
